const menu=document.querySelector('.menu');const links=document.querySelector('.links');menu.addEventListener('click',()=>links.classList.toggle('open'));document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));document.getElementById('year').textContent=new Date().getFullYear();

const serviceData={
 hvac:{kicker:'HOME COMFORT',title:'HVAC Service That Comes To You',copy:'When your AC stops cooling or your heat is not keeping up, we help diagnose common HVAC issues and get you moving toward a solution without the runaround.',list:['AC not cooling','Heating problems','Thermostat issues','Airflow concerns','System troubleshooting'],label:'HVAC'},
 electrical:{kicker:'HOME ELECTRICAL',title:'Practical Electrical Help At Your Location',copy:'From outlets and switches to lighting and common electrical concerns, tell us what is happening and we will help determine the right next step for your home.',list:['Outlet problems','Switch replacement','Lighting issues','Common troubleshooting','Minor electrical repairs'],label:'Electrical'},
 brakes:{kicker:'MOBILE AUTO',title:'Brake Service Without The Shop Wait',copy:'Hearing squeaks or grinding, feeling vibration, or simply due for brake service? We bring convenient brake inspection and common brake service to your location.',list:['Brake inspection','Brake pads','Rotor concerns','Squeaking or grinding','Stopping-performance issues'],label:'Brake Service'},
 oil:{kicker:'MOBILE MAINTENANCE',title:'Oil Changes On Your Schedule',copy:'Keep your vehicle maintained without losing time at a waiting room. We provide convenient mobile oil and filter service at your home, workplace, or other approved location.',list:['Oil & filter change','Routine maintenance','Fluid visual checks','Maintenance reminders','On-site convenience'],label:'Oil Change'},
 battery:{kicker:'MOBILE AUTO',title:'Battery & Starting Help',copy:'Car slow to start or not starting at all? Contact us for common battery and starting-system help at your location.',list:['Battery concerns','No-start checks','Battery replacement help','Terminal inspection','Basic starting diagnostics'],label:'Battery & Starting'},
 minorauto:{kicker:'MOBILE AUTO',title:'Minor Auto Repairs, Where You Are',copy:'For everyday vehicle issues that may not require a full repair shop visit, tell us what is happening and we will confirm whether mobile service is a fit.',list:['Minor maintenance','Common replacement items','Basic troubleshooting','Convenience repairs','Service assessment'],label:'Minor Auto Repair'},
 homefix:{kicker:'HOME SERVICES',title:'Everyday Home Repairs Made Easier',copy:'Something around the house stopped working? Describe the problem and we will confirm whether it is within our mobile service scope.',list:['Minor household fixes','Fixture concerns','Basic troubleshooting','Maintenance help','Service assessment'],label:'Home Repairs'},
 diagnostics:{kicker:'FIND THE PROBLEM',title:'Start With Smart Troubleshooting',copy:'Not sure what is wrong? Call or text us the symptoms. We can help narrow down the issue and determine whether an on-site visit makes sense.',list:['Describe the symptoms','Initial troubleshooting','Home or auto concerns','Next-step guidance','On-site assessment'],label:'Diagnostics'}
};
function showService(key,scroll=false){const d=serviceData[key];if(!d)return;document.getElementById('detail-kicker').textContent=d.kicker;document.getElementById('detail-title').textContent=d.title;document.getElementById('detail-copy').textContent=d.copy;document.getElementById('detail-list').innerHTML=d.list.map(x=>`<li>${x}</li>`).join('');const t=document.getElementById('detail-text');t.textContent=`Text About ${d.label}`;t.href=`sms:+12149032157?body=${encodeURIComponent(`Hi 1Call Home Auto, I need help with ${d.label}.`)}`;document.querySelectorAll('.service-card').forEach(c=>c.classList.toggle('active',c.dataset.service===key));if(scroll)document.getElementById('service-detail').scrollIntoView({behavior:'smooth',block:'center'});}
document.querySelectorAll('[data-service]').forEach(el=>el.addEventListener('click',()=>showService(el.dataset.service,true)));
